### ISSUE TITLE
No link back to repository on npmjs.com

### ISSUE THREAD

**Issue by webbertakken** [ricardo-ch/jest-fail-on-console#1]
Hi Ricardo,

Thanks for creating this package!

Little point of feedback: Usually npm packages refer back to the code from [this page](https://www.npmjs.com/package/jest-fail-on-console).

**Comment by KevinHerklotz** [comment]
@ValentinH, I added the correct link, but I cannot publish (maybe I don't even need to for npm to update?)

**Comment by ValentinH** [comment]
Published it with v2.0.4.
