### ISSUE TITLE
Customize error message

### ISSUE THREAD

**Issue by JCB-K** [ricardo-ch/jest-fail-on-console#11]
Hi!

Thanks for a great package :). Would you accept a PR that allows an optional config option for a custom error message? We want to adopt this package, but I'm afraid that the default message will nudge maintainers to just mock console.error as an easy way out, even when errors aren't expected. A custom error message would allow me to link to an internal documentation page with our common errors and how to handle them.

**Comment by ValentinH** [comment]
Thank you for the kind words!
Yes I would accept such a PR 🙂 

Moreover, if you have ideas to improve the default one in a way that would be more helpful for the community, you are welcome ! 🎉
