### ISSUE TITLE
Add `mockImplementation` info to warning message.

### ISSUE THREAD

**Issue by SDRACK** [ricardo-ch/jest-fail-on-console#9]
I wonder if it's worth adding the info about `mockImplementation` from the readme ([here](https://github.com/ricardo-ch/jest-fail-on-console#but-i-have-some-expected-console-errorswarning)) to the warning message this package throws?

I'm pretty new to Jest, and didn't pick that up from the existing error message:

>If the error is expected, test for it explicitly by mocking it out using jest.spyOn(console, 'error') and test that the warning occurs.

(An aside, love the package - it's been really helpful for us.)

**Comment by ValentinH** [comment]
Yes I think this could be nice. Would you like to create a PR for this?
